/** Bump when BLOCKED_KEYWORD_TERMS or categories change; keep 040 + 052 + 053 seeds in sync. */
export const KEYWORD_LIST_VERSION = "1.2.0";

export type BlockedKeywordCategory =
  | "profanity"
  | "bullying"
  | "self_harm"
  | "personal_info"
  | "off_platform"
  | "spam"
  | "obscenity";

export const OBSCENITY_PHRASE_TERMS = [
  "porno izle",
  "porn izle",
  "çıplak foto",
  "ciplak foto",
  "çıplak video",
  "ciplak video",
  "seks videosu",
  "seks video",
  "müstehcen video",
  "mustehcen video",
  "erotik video",
  "nsfw içerik",
  "nsfw icerik",
  "+18",
  "18+",
  "yetişkin içerik",
  "yetiskin icerik",
  "adult content",
  "plus 18",
] as const;

export const OBSCENITY_KEYWORD_TERMS = [
  "müstehcen",
  "mustehcen",
  "yetişkin",
  "yetiskin",
  "porno",
  "pornografi",
  "pornhub",
  "onlyfans",
  "xvideos",
  "xhamster",
  "çıplak",
  "ciplak",
  "çıplaklık",
  "ciplaklik",
  "erotik",
  "nsfw",
  "nude",
  "naked",
  "xxx",
  "hentai",
  "sikiş",
  "sikis",
  "seviş",
  "sevis",
  "masturbasyon",
  "masturb",
  "fuhuş",
  "fuhus",
  "escort",
  "amcık",
  "amcik",
  "yarrak",
  "softcore",
  "hardcore",
] as const;

/** Leetspeak / aralıklı yazım kaçakları (normalize + compact sonrası). */
export const OBSCENITY_COMPACT_PATTERNS = [
  /^porn/i,
  /^p0rn/i,
  /pornhub/i,
  /onlyfans/i,
  /xvideos/i,
  /xhamster/i,
  /nsfw/i,
  /hentai/i,
  /xxx+/i,
  /nude/i,
  /mustehcen/i,
  /müstehcen/i,
] as const;

export const SAFETY_KEYWORD_TERMS = [
  "salak",
  "aptal",
  "gerizekali",
  "gerizekalı",
  "mal",
  "ezik",
  "kufur",
  "küfür",
  "siktir",
  "bok",
  "orospu",
  "pic",
  "piç",
  "zorbalik",
  "zorbalık",
  "dalga geç",
  "disla",
  "dışla",
  "kendini oldur",
  "kendini öldür",
  "geber",
  "olsen iyi",
  "ölsen iyi",
  "adresim",
  "telefonum",
  "okulum",
  "evim",
  "whatsapp",
  "telegram",
  "snap",
  "discord",
  "mesaj at",
  "özelden",
] as const;

export const BLOCKED_KEYWORD_TERMS = [
  ...SAFETY_KEYWORD_TERMS,
  ...OBSCENITY_PHRASE_TERMS,
  ...OBSCENITY_KEYWORD_TERMS,
] as const;

export const BLOCKED_KEYWORD_CATEGORIES: Record<string, BlockedKeywordCategory> = {
  salak: "profanity",
  aptal: "profanity",
  gerizekali: "profanity",
  "gerizekalı": "profanity",
  mal: "profanity",
  ezik: "bullying",
  kufur: "profanity",
  "küfür": "profanity",
  siktir: "profanity",
  bok: "profanity",
  orospu: "profanity",
  pic: "profanity",
  "piç": "profanity",
  zorbalik: "bullying",
  "zorbalık": "bullying",
  "dalga geç": "bullying",
  disla: "bullying",
  "dışla": "bullying",
  "kendini oldur": "self_harm",
  "kendini öldür": "self_harm",
  geber: "self_harm",
  "olsen iyi": "self_harm",
  "ölsen iyi": "self_harm",
  adresim: "personal_info",
  telefonum: "personal_info",
  okulum: "personal_info",
  evim: "personal_info",
  whatsapp: "off_platform",
  telegram: "off_platform",
  snap: "off_platform",
  discord: "off_platform",
  "mesaj at": "off_platform",
  "özelden": "off_platform",
  "porno izle": "obscenity",
  "porn izle": "obscenity",
  "çıplak foto": "obscenity",
  "ciplak foto": "obscenity",
  "çıplak video": "obscenity",
  "ciplak video": "obscenity",
  "seks videosu": "obscenity",
  "seks video": "obscenity",
  "müstehcen video": "obscenity",
  "mustehcen video": "obscenity",
  "erotik video": "obscenity",
  "nsfw içerik": "obscenity",
  "nsfw icerik": "obscenity",
  "+18": "obscenity",
  "18+": "obscenity",
  "yetişkin içerik": "obscenity",
  "yetiskin icerik": "obscenity",
  "adult content": "obscenity",
  "plus 18": "obscenity",
  "müstehcen": "obscenity",
  mustehcen: "obscenity",
  "yetişkin": "obscenity",
  yetiskin: "obscenity",
  porno: "obscenity",
  pornografi: "obscenity",
  pornhub: "obscenity",
  onlyfans: "obscenity",
  xvideos: "obscenity",
  xhamster: "obscenity",
  "çıplak": "obscenity",
  ciplak: "obscenity",
  "çıplaklık": "obscenity",
  ciplaklik: "obscenity",
  erotik: "obscenity",
  nsfw: "obscenity",
  nude: "obscenity",
  naked: "obscenity",
  xxx: "obscenity",
  hentai: "obscenity",
  "sikiş": "obscenity",
  sikis: "obscenity",
  "seviş": "obscenity",
  sevis: "obscenity",
  masturbasyon: "obscenity",
  masturb: "obscenity",
  "fuhuş": "obscenity",
  fuhus: "obscenity",
  escort: "obscenity",
  "amcık": "obscenity",
  amcik: "obscenity",
  yarrak: "obscenity",
  softcore: "obscenity",
  hardcore: "obscenity",
};

export const SUSPICIOUS_PATTERNS = [
  /(.)\1{5,}/i,
  /\b(dm)\b/i,
] as const;

export function categoryToModerationReason(
  category: BlockedKeywordCategory,
): "profanity" | "bullying" | "self_harm" | "personal_info" | "off_platform_contact" | "spam" | "obscenity" {
  if (category === "off_platform") return "off_platform_contact";
  return category;
}
